#version: '3.8'
services:
  db:
    image: postgres:13.4
    container_name: apple_stock_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_data
    ports:
      - "5432:5432"
